version: "3.7"

services:
  mongo-db:
    image: mongo
    container_name: mongodb
    restart: on-failure
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dbuser
      - MONGO_INITDB_ROOT_PASSWORD=dbpassword
      - MONGO_DATA_DIR=/data/db
    volumes:
      - mongodb_data:/data/db
    networks:
      - default
networks:
  default:
    external:
      name: sky-net
volumes:
  mongodb_data: