version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:3.8.4-management
    restart: on-failure
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - 5672:5672
      - 15672:15672
      - 15675:15675
      - 1883:1883
      - 25672:25672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - default
volumes:
  rabbitmq_data:
networks:
  default:
    external:
      name: sky-net